<?php
$tableId='documentos-table';
$tablePageSize=10;
$tableFilters=[
 ['label'=>'Pesquisa geral','column'=>'*','type'=>'search','placeholder'=>'Documento, fornecedor, obrigação ou SEI','class'=>'col-12 col-lg-4'],
 ['label'=>'Fornecedor','column'=>1,'type'=>'select','populate'=>true,'empty'=>'Todos','class'=>'col-12 col-md-4 col-lg-2'],
 ['label'=>'Inspeção','column'=>4,'type'=>'select','populate'=>true,'empty'=>'Todos','class'=>'col-12 col-md-4 col-lg-2'],
];
$obrigacaoSelecionada=(int)($_GET['obrigacao_id']??0);
?>
<div class="row g-3"><div class="col-xl-4"><div class="card"><div class="card-header"><h3 class="card-title">Lançar documento</h3></div><form method="post" action="/documentos"><div class="card-body"><div class="mb-3"><label class="form-label">Obrigação</label><select name="obrigacao_id" class="form-select" required><option value="">Selecione</option><?php foreach($obrigacoes as $o):?><option value="<?=e($o['id'])?>" <?=((int)$o['id']===$obrigacaoSelecionada)?'selected':''?>><?=e($o['tipo'])?> <?=e($o['numero'])?>/<?=e($o['ano'])?> — <?=e($o['fornecedor'])?></option><?php endforeach;?></select></div><div class="mb-3"><label class="form-label">Tipo do documento</label><select name="tipo_documento_id" class="form-select" required><option value="">Selecione</option><?php foreach($tipos as $t):?><option value="<?=e($t['id'])?>"><?=e($t['nome'])?></option><?php endforeach;?></select></div><div class="row"><div class="col-7 mb-3"><label class="form-label">Número</label><input name="numero" class="form-control" required></div><div class="col-5 mb-3"><label class="form-label">Data</label><input type="date" name="data_documento" class="form-control" required></div></div><div class="mb-3"><label class="form-label">Valor bruto</label><input name="valor_bruto" class="form-control" required placeholder="0,00"></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Data máxima liquidação</label><input type="date" name="data_maxima_liquidacao" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label">Limite anotação</label><input type="date" name="limite_anotacao" class="form-control"></div></div><div class="mb-3"><label class="form-label">Data do atesto</label><input type="date" name="data_atesto" class="form-control"></div><div class="mb-3"><label class="form-label">Tipo de serviço</label><input name="tipo_servico" class="form-control"></div><div class="mb-3"><label class="form-label">Nº SEI pagamento</label><input name="sei_pagamento" class="form-control"></div><div class="mb-3"><label class="form-label">Observações</label><textarea name="observacoes" class="form-control" rows="3"></textarea></div><div class="form-text">A data/hora do lançamento é registrada automaticamente pelo sistema.</div></div><div class="card-footer"><button class="btn btn-primary"><i class="fa-solid fa-plus me-1"></i>Lançar</button></div></form></div></div>
<div class="col-xl-8"><div class="card" data-admin-table data-page-size="<?=$tablePageSize?>"><div class="card-header"><h3 class="card-title">Documentos lançados</h3></div><?php require BASE_PATH.'/app/views/components/admin_table_filters.php';?><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover table-striped mb-0 align-middle"><thead><tr><th>Documento</th><th>Fornecedor</th><th>Obrigação</th><th>Valor</th><th>Inspeção</th><th>Lançamento</th><th class="text-end portal-actions-cell" data-table-nosort>Ações</th></tr></thead><tbody><?php foreach($documentos as $d):?><tr data-record-id="<?=e($d['id'])?>"><td><strong><?=e($d['tipo_documento'])?> <?=e($d['numero'])?></strong><div class="small text-body-secondary"><?=e($d['data_documento'])?></div></td><td><?=e($d['fornecedor'])?></td><td><?=e($d['obrigacao_numero'])?>/<?=e($d['obrigacao_ano'])?></td><td class="money"><?=money($d['valor_bruto'])?></td><td><span class="badge <?=$d['permite_avancar']?'text-bg-success':'text-bg-warning'?>"><?=e($d['status_inspecao']??'Aguardando')?></span></td><td><?=e($d['data_lancamento'])?></td><td class="text-end portal-actions-cell"><div class="portal-action-group portal-table-actions justify-content-end"><a href="/documentos/<?=e($d['id'])?>" class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i>Abrir</a></div></td></tr><?php endforeach;?><?php if(!$documentos):?><tr data-table-empty><td colspan="7" class="text-center text-body-secondary py-4">Nenhum documento lançado.</td></tr><?php endif;?></tbody></table></div></div><?php require BASE_PATH.'/app/views/components/admin_table_footer.php';?></div></div></div>
<?php unset($tableId,$tablePageSize,$tableFilters,$obrigacaoSelecionada);?>
