<?php
$tableId='inspecoes-table';
$tablePageSize=10;
$tableFilters=[
 ['label'=>'Pesquisa geral','column'=>'*','type'=>'search','placeholder'=>'Documento, fornecedor ou obrigação','class'=>'col-12 col-lg-4'],
 ['label'=>'Status','column'=>4,'type'=>'select','populate'=>true,'empty'=>'Todos','class'=>'col-12 col-md-4 col-lg-2'],
 ['label'=>'Fornecedor','column'=>1,'type'=>'select','populate'=>true,'empty'=>'Todos','class'=>'col-12 col-md-4 col-lg-2'],
];
?>
<div class="card" data-admin-table data-page-size="<?=$tablePageSize?>"><div class="card-header"><h3 class="card-title">Documentos aguardando ou em inspeção</h3></div><?php require BASE_PATH.'/app/views/components/admin_table_filters.php';?><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover table-striped mb-0 align-middle"><thead><tr><th>Documento</th><th>Fornecedor</th><th>Obrigação</th><th>Valor</th><th>Status</th><th>Lançamento</th><th class="text-end portal-actions-cell" data-table-nosort>Ações</th></tr></thead><tbody><?php foreach($itens as $i):?><tr data-record-id="<?=e($i['documento_id'])?>"><td><strong><?=e($i['tipo_documento'])?> <?=e($i['documento_numero'])?></strong><div class="small text-body-secondary"><?=e($i['data_documento'])?></div></td><td><?=e($i['fornecedor'])?></td><td><?=e($i['obrigacao_numero'])?>/<?=e($i['obrigacao_ano'])?></td><td><?=money($i['valor_bruto'])?></td><td><span class="badge <?=$i['permite_avancar']?'text-bg-success':'text-bg-warning'?>"><?=e($i['status_inspecao'])?></span></td><td><?=e($i['data_lancamento'])?></td><td class="text-end portal-actions-cell"><div class="portal-action-group portal-table-actions justify-content-end"><a href="/documentos/<?=e($i['documento_id'])?>" class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i>Inspecionar</a></div></td></tr><?php endforeach;?><?php if(!$itens):?><tr data-table-empty><td colspan="7" class="text-center text-body-secondary py-4">Fila vazia.</td></tr><?php endif;?></tbody></table></div></div><?php require BASE_PATH.'/app/views/components/admin_table_footer.php';?></div>
<?php unset($tableId,$tablePageSize,$tableFilters);?>