<?php
$tableId='liquidacoes-table';
$tablePageSize=10;
$tableFilters=[
 ['label'=>'Pesquisa geral','column'=>'*','type'=>'search','placeholder'=>'Documento, fornecedor ou empenho','class'=>'col-12 col-lg-4'],
 ['label'=>'Status','column'=>5,'type'=>'select','populate'=>true,'empty'=>'Todos','class'=>'col-12 col-md-4 col-lg-2'],
 ['label'=>'Fornecedor','column'=>1,'type'=>'select','populate'=>true,'empty'=>'Todos','class'=>'col-12 col-md-4 col-lg-2'],
];
?>
<div class="card" data-admin-table data-page-size="<?=$tablePageSize?>"><div class="card-header"><h3 class="card-title">Parcelas para liquidação</h3></div><?php require BASE_PATH.'/app/views/components/admin_table_filters.php';?><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover table-striped mb-0 align-middle"><thead><tr><th>Documento / Parcela</th><th>Fornecedor</th><th>Empenho</th><th>Parcela</th><th>Composição</th><th>Status</th><th class="text-end portal-actions-cell" data-table-nosort>Ações</th></tr></thead><tbody><?php foreach($itens as $i):?><?php $composicaoOk=round((float)$i['valor_total'],2)===round((float)$i['soma_componentes'],2);?><tr data-record-id="<?=e($i['parcela_id'])?>"><td><strong><?=e($i['tipo_documento'])?> <?=e($i['documento_numero'])?></strong><div class="small">Parcela <?=e($i['numero_parcela'])?></div></td><td><?=e($i['fornecedor'])?></td><td><?=e($i['empenho_numero'])?>/<?=e($i['empenho_ano'])?></td><td><?=money($i['valor_total'])?></td><td><span class="<?=$composicaoOk?'text-success':'text-danger'?>"><?=money($i['soma_componentes'])?></span></td><td><span class="badge <?=$i['status']==='CONCLUIDA'?'text-bg-success':'text-bg-warning'?>"><?=e($i['status'])?></span><?php if($i['data_liquidacao']):?><div class="small"><?=e($i['data_liquidacao'])?></div><?php endif;?></td><td class="text-end portal-actions-cell"><div class="portal-action-group portal-table-actions justify-content-end"><a href="/documentos/<?=e($i['documento_id'])?>" class="btn btn-sm btn-outline-primary"><i class="fa-solid <?=$i['status']==='CONCLUIDA'?'fa-arrow-up-right-from-square':'fa-check-double'?>" aria-hidden="true"></i><?=$i['status']==='CONCLUIDA'?'Abrir':'Liquidar'?></a></div></td></tr><?php endforeach;?><?php if(!$itens):?><tr data-table-empty><td colspan="7" class="text-center text-body-secondary py-4">Fila vazia.</td></tr><?php endif;?></tbody></table></div></div><?php require BASE_PATH.'/app/views/components/admin_table_footer.php';?></div>
<?php unset($tableId,$tablePageSize,$tableFilters,$composicaoOk);?>