<?php
$tableId='programacao-table';
$tablePageSize=10;
$tableFilters=[
 ['label'=>'Pesquisa geral','column'=>'*','type'=>'search','placeholder'=>'Documento ou fornecedor','class'=>'col-12 col-lg-4'],
 ['label'=>'Situação','column'=>5,'type'=>'select','populate'=>true,'empty'=>'Todas','class'=>'col-12 col-md-4 col-lg-2'],
 ['label'=>'Fornecedor','column'=>1,'type'=>'select','populate'=>true,'empty'=>'Todos','class'=>'col-12 col-md-4 col-lg-2'],
];
?>
<div class="card" data-admin-table data-page-size="<?=$tablePageSize?>"><div class="card-header"><h3 class="card-title">Documentos liberados pela inspeção</h3></div><?php require BASE_PATH.'/app/views/components/admin_table_filters.php';?><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover table-striped mb-0 align-middle"><thead><tr><th>Documento</th><th>Fornecedor</th><th>Valor</th><th>Programado</th><th>Saldo</th><th>Situação</th><th class="text-end portal-actions-cell" data-table-nosort>Ações</th></tr></thead><tbody><?php foreach($itens as $i):?><?php $fechado=round((float)$i['saldo_programar'],2)===0.0;?><tr data-record-id="<?=e($i['documento_id'])?>"><td><strong><?=e($i['tipo_documento'])?> <?=e($i['documento_numero'])?></strong></td><td><?=e($i['fornecedor'])?></td><td><?=money($i['valor_bruto'])?></td><td><?=money($i['valor_programado'])?></td><td><?=money($i['saldo_programar'])?></td><td><span class="badge <?=$fechado?'text-bg-success':'text-bg-warning'?>"><?=$fechado?'Fechado':'A programar'?></span></td><td class="text-end portal-actions-cell"><div class="portal-action-group portal-table-actions justify-content-end"><a href="/documentos/<?=e($i['documento_id'])?>" class="btn btn-sm btn-outline-primary"><i class="fa-solid fa-list-check" aria-hidden="true"></i><?=$fechado?'Abrir':'Programar'?></a></div></td></tr><?php endforeach;?><?php if(!$itens):?><tr data-table-empty><td colspan="7" class="text-center text-body-secondary py-4">Nenhum documento liberado para programação.</td></tr><?php endif;?></tbody></table></div></div><?php require BASE_PATH.'/app/views/components/admin_table_footer.php';?></div>
<?php unset($tableId,$tablePageSize,$tableFilters,$fechado);?>