<?php
$tableId='usuarios-table';
$tablePageSize=10;
$tableFilters=[
 ['label'=>'Pesquisa geral','column'=>'*','type'=>'search','placeholder'=>'Nome, login ou e-mail','class'=>'col-12 col-lg-4'],
 ['label'=>'Perfil','column'=>2,'type'=>'select','populate'=>true,'empty'=>'Todos','class'=>'col-12 col-md-4 col-lg-2'],
 ['label'=>'Status','column'=>4,'type'=>'select','populate'=>true,'empty'=>'Todos','class'=>'col-12 col-md-4 col-lg-2'],
];
$usuarioAtualId=(int)(Auth::user()['id']??0);
?>
<div class="row g-3"><div class="col-xl-4"><div class="card"><div class="card-header"><h3 class="card-title">Novo usuário</h3></div><form method="post" action="/usuarios"><div class="card-body"><div class="mb-3"><label class="form-label">Nome</label><input name="nome" class="form-control" required></div><div class="mb-3"><label class="form-label">Login</label><input name="login" class="form-control" required></div><div class="mb-3"><label class="form-label">E-mail</label><input type="email" name="email" class="form-control"></div><div class="mb-3"><label class="form-label">Perfil</label><select name="perfil_id" class="form-select" required><option value="">Selecione</option><?php foreach($perfis as $p):?><option value="<?=e($p['id'])?>"><?=e($p['nome'])?></option><?php endforeach;?></select></div><div class="mb-3"><label class="form-label">Senha</label><input type="password" name="senha" minlength="8" class="form-control" required></div></div><div class="card-footer"><button class="btn btn-primary"><i class="fa-solid fa-user-plus me-1"></i>Cadastrar</button></div></form></div></div>
<div class="col-xl-8"><div class="card" data-admin-table data-page-size="<?=$tablePageSize?>"><div class="card-header"><h3 class="card-title">Usuários cadastrados</h3></div><?php require BASE_PATH.'/app/views/components/admin_table_filters.php';?><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover table-striped mb-0 align-middle"><thead><tr><th>Nome</th><th>Login</th><th>Perfil</th><th>E-mail</th><th>Status</th><th class="text-end portal-actions-cell" data-table-nosort>Ações</th></tr></thead><tbody><?php foreach($usuarios as $u):?><?php $ehAtual=(int)$u['id']===$usuarioAtualId;?><tr data-record-id="<?=e($u['id'])?>"><td><?=e($u['nome'])?></td><td><?=e($u['login'])?></td><td><?=e($u['perfil'])?></td><td><?=e($u['email'])?></td><td><span class="badge <?=$u['ativo']?'text-bg-success':'text-bg-secondary'?>"><?=$u['ativo']?'Ativo':'Inativo'?></span></td><td class="text-end portal-actions-cell"><div class="portal-action-group portal-table-actions justify-content-end"><form method="post" action="/usuarios/<?=e($u['id'])?>/status" onsubmit="return confirm('<?=e($u['ativo']?'Desativar':'Ativar')?> este usuário?')"><button type="submit" class="btn btn-sm <?=$u['ativo']?'btn-outline-warning':'btn-outline-success'?>" <?=$ehAtual?'disabled title="Usuário atualmente logado"':''?>><i class="fa-solid <?=$u['ativo']?'fa-ban':'fa-check'?>" aria-hidden="true"></i><?=$u['ativo']?'Desativar':'Ativar'?></button></form></div></td></tr><?php endforeach;?><?php if(!$usuarios):?><tr data-table-empty><td colspan="6" class="text-center text-body-secondary py-4">Nenhum usuário cadastrado.</td></tr><?php endif;?></tbody></table></div></div><?php require BASE_PATH.'/app/views/components/admin_table_footer.php';?></div></div></div>
<?php unset($tableId,$tablePageSize,$tableFilters,$usuarioAtualId,$ehAtual);?>
